### ISSUE TITLE
The role of the 'use_syntax' variable

### ISSUE THREAD

**Issue by teenevin28** [dksanyal/SpERT.PL#1]
Thank you team for sharing the source code.
I am a student and currently researching SpERT.
I have a question about the 'use_syntax' variable. It was mentioned in the source code, and I believe the team might have used it for the entire syntax tree, but it wasn't referenced in the code or in the paper. 
Therefore, I am earnestly interested in learning about the team's previous idea for the 'use_syntax' variable. 
I hope the team can take the time to care and help me with my inquiries. I sincerely appreciate it.

**Comment by dksanyal** [comment]
It was not used finally; we used only POS tags. We had initially thought of
using the syntax to augment the input to the model.  You might like to
implement the extension. This paper could be useful in this context:
https://aclanthology.org/2021.eacl-main.228.pdf.

**Comment by teenevin28** [comment]
This is such a valuable piece of information, thank you for sharing!
